services:
  postgres:
    image: postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: wavepoll
      POSTGRES_USER: wavepoll
      POSTGRES_PASSWORD: wavepoll
    volumes:
      - wavepoll_postgres:/var/lib/postgresql
  redis:
    image: redis
    command: redis-server --maxmemory-policy noeviction
    ports:
      - "6379:6379"
    volumes:
      - wavepoll_redis:/data
  serverless-redis-http:
    ports:
      - "8079:80"
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: wavepoll
      SRH_CONNECTION_STRING: "redis://redis:6379"
  minio:
    image: cgr.dev/chainguard/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=wavepoll
      - MINIO_ROOT_PASSWORD=wavepoll
    volumes:
      - wavepoll_minio:/data
    command: ["server", "/data", "--console-address", ":9001"]

volumes:
  wavepoll_postgres:
  wavepoll_redis:
  wavepoll_minio:
